services:
  litellm:
    image: ghcr.io/berriai/litellm:main-v1.82.4-nightly
    container_name: litellm-proxy
    ports:
      - "127.0.0.1:4000:4000"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
      - ./.env:/app/.env
      - ./data:/root/.litellm
      - ./auth:/root/.config/litellm
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["--config", "/app/config.yaml", "--port", "4000"]
    restart: always
